version: "2"

linters:
  enable:
    - importas
    - govet
    - errcheck
    - staticcheck
    - unused
  settings:
    importas:
      no-unaliased: false
      alias:
        - pkg: github.com/lmarqs/terraform-ui/plugins/apply
          alias: tfuiapply
        - pkg: github.com/lmarqs/terraform-ui/plugins/blastradius
          alias: tfuiblast
        - pkg: github.com/lmarqs/terraform-ui/plugins/chdir
          alias: tfuichdir
        - pkg: github.com/lmarqs/terraform-ui/plugins/context
          alias: tfuicontext
        - pkg: github.com/lmarqs/terraform-ui/plugins/output
          alias: tfuioutput
        - pkg: github.com/lmarqs/terraform-ui/plugins/phantom
          alias: tfuiphantom
        - pkg: github.com/lmarqs/terraform-ui/plugins/plan
          alias: tfuiplan
        - pkg: github.com/lmarqs/terraform-ui/plugins/repl
          alias: tfuirepl
        - pkg: github.com/lmarqs/terraform-ui/plugins/risk
          alias: tfuirisk
        - pkg: github.com/lmarqs/terraform-ui/plugins/state
          alias: tfuistate
        - pkg: github.com/lmarqs/terraform-ui/plugins/validate
          alias: tfuivalidate
        - pkg: github.com/lmarqs/terraform-ui/plugins/workspaces
          alias: tfuiworkspaces
        - pkg: github.com/charmbracelet/bubbletea
          alias: tea
    errcheck:
      exclude-functions:
        - (io.Closer).Close
  exclusions:
    rules:
      - path: _test\.go
        linters:
          - errcheck

formatters:
  enable:
    - goimports

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
