version: "2"

linters:
  enable:
    - importas
    - govet
    - errcheck
    - staticcheck
    - unused
  settings:
    importas:
      no-unaliased: false
      alias:
        - pkg: github.com/lmarqs/terraform-ui/plugins/blastradius
          alias: tfuiblast
        - pkg: github.com/lmarqs/terraform-ui/plugins/(.+)
          alias: tfui$1
        - pkg: github.com/charmbracelet/bubbletea
          alias: tea
    errcheck:
      exclude-functions:
        - (io.Closer).Close
  exclusions:
    rules:
      - path: _test\.go
        linters:
          - errcheck

formatters:
  enable:
    - goimports

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
