version: 2

builds:
  - id: tfui
    main: ./cmd/tfui
    binary: tfui
    ldflags:
      - -s -w -X main.version={{.Version}}
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64

archives:
  - formats:
      - tar.gz
    name_template: "tfui_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

release:
  mode: append

changelog:
  disable: true
