name: prepare_env

runs:
  using: composite
  steps:
    - name: Install Mise
      uses: jdx/mise-action@v2
      with:
        cache: true

    - name: Install dependencies
      shell: bash
      run: mise run setup
