name: Build

on:
  workflow_call:

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/prepare-env
      - run: mise run check:lint

  unit:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    permissions:
      checks: write
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/prepare-env
      - run: mise run test:unit
      - uses: dorny/test-reporter@v1
        if: always()
        with:
          name: Tests (${{ matrix.os }})
          path: reports/*.xml
          reporter: java-junit

  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/prepare-env
      - run: mise run test:coverage

  binaries:
    needs: [lint, unit, coverage]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: ./.github/actions/prepare-env
      - run: mise run build
      - uses: actions/upload-artifact@v4
        with:
          name: binaries
          path: dist/
          retention-days: 1
