name: CI

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize]
    branches: [main]

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build:
    uses: ./.github/workflows/build.yaml
    permissions:
      checks: write
      contents: read

  test:
    needs: build
    uses: ./.github/workflows/test.yaml
    permissions:
      contents: read

  release:
    if: github.event_name == 'push'
    needs: test
    uses: ./.github/workflows/release.yaml
    permissions:
      actions: write
      contents: write
