name: Test

on:
  workflow_call:

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  macro:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/prepare-env
      - uses: actions/download-artifact@v4
        with:
          name: binaries
          path: dist/
      - run: chmod +x dist/tfui_linux_amd64_v1/tfui
      - run: mise run test:macro dist/tfui_linux_amd64_v1/tfui

  integration:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/prepare-env
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.14"
          terraform_wrapper: false
      - run: mise run test:integration
